version: '3.1'

services:
  postgres:
    image: postgres:9.6
    container_name: chameleon_postgres
    restart: always
    command: -p 9999
    ports:
      - '9999:9999'
    environment:
      POSTGRES_USER: changeme027a023931d22
      POSTGRES_PASSWORD: changeme0f40323877963
    logging:
        driver: none
  
  grafana:
    build: ./grafana
    container_name: grafana
    command: ./import.sh
    ports:
      - '3000:3000'
    links:
      - postgres
    environment:
      GF_SECURITY_ADMIN_USER: tareaEnigmaHoneypotsGrafico
      GF_SECURITY_ADMIN_PASSWORD: tareaEnigmaHoneypotsGrafico6583682147104328
    logging:
        driver: none
  
  honeypots:
    build:
      context: .
      dockerfile: ./honeypots-Dockerfile
    container_name: honeypots
    network_mode: "host"
    # ports:
    #   - '21:21'
    #   - '443:443'
    depends_on:
      - postgres

  s7:
    build:
      context: .
      dockerfile: ./s7plus-Dockerfile
    container_name: s7
    ports:
      - '102:102'

networks:
  frontend:
    internal: false
  backend:
    internal: true