version: '3.1'

services:
  postgres:
    image: postgres:9.6
    container_name: chameleon_postgres
    restart: always
    command: -p 9999
    ports:
      - '9999:9999'
    environment:
      POSTGRES_USER: changeme027a088931d22
      POSTGRES_PASSWORD: changeme0f40773877963
    logging:
        driver: none
  
  grafana:
    build: ./grafana
    container_name: grafana
    command: ./import.sh
    ports:
      - '3000:3000'
    links:
      - postgres
    environment:
      GF_SECURITY_ADMIN_USER: changeme457f6460cb287
      GF_SECURITY_ADMIN_PASSWORD: changemed23b8cc6a20e0
    logging:
        driver: none
  
  honeypots:
    build:
      context: .
      dockerfile: ./honeypots-Dockerfile
    container_name: honeypots
    network_mode: "host"
    ports:
      - '21:21'
      - '443:443'
    depends_on:
      - postgres

networks:
  frontend:
    internal: false
  backend:
    internal: true