{
 "title": "Chameleon",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "IP",
    "label": "IP",
    "query": "SELECT\n  (data->>'src_ip')\nFROM\n  sniffer_table\nLIMIT 1"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FTP Login",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%' AND data->>'action' LIKE '%login%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%' AND data->>'action' LIKE '%login%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%ftp_server%' AND data->>'status'  <> '' AND (data->>'src_ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "HTTPS Login",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%' AND data->>'action' LIKE '%login%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%' AND data->>'action' LIKE '%login%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%https_server%' AND data->>'status'  <> '' AND (data->>'src_ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "Worldmap",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 14, "x": 10, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  data->'src_ip'->>'ip' as ip,\n  data->'src_ip'->'geo'->> 'latitude' as latitude,\n  data->'src_ip'->'geo'->> 'longitude' as longitude,\n  COUNT(*) as metric\nFROM\n  servers_table\nWHERE\n  $__timeFilter(date) AND data->>'action' LIKE '%connection%' AND (data->> 'server' LIKE '%https_server%' OR data->> 'server' LIKE '%ftp_server%') AND data->>'src_ip' <> ''  AND (data->>'src_ip') LIKE '%$IP%'\nGROUP BY data->'src_ip'->'geo'->> 'latitude',\n  data->'src_ip'->'geo'->> 'longitude',\n  data->'src_ip'->>'ip';\n"
    }
   ]
  },
  {
   "title": "All Creds",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT data->>'src_ip' as ip,\n       data->>'username' as username,\n       data->>'password' as password,\n       data->>'server' as server\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'action' LIKE '%login%' AND data->>'src_ip' <> ''  AND (data->>'src_ip') LIKE '%$IP%'\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "All HTTPS Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT data->>'src_ip' as ip,\n       data->>'action' as method,\n       data->'data'->>'uri' as uri,\n       data->>'data' as headers\nFROM   servers_table\nWHERE  $__timeFilter(date) AND (data->>'action' LIKE '%GET%' OR data->>'action' LIKE '%POST%') AND data->> 'server' LIKE '%https_server%' AND data->>'src_ip' <> ''  AND (data->>'src_ip') LIKE '%$IP%'\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "All FTP Commands",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT data->>'src_ip' as ip,\n       data->'data'->>'cmd' as command,\n       replace(substring(data->'data'->>'args' from 2 for length(data->'data'->>'args') - 2),',',' ') as arguments\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'action' LIKE '%command%' AND data->> 'server' LIKE '%ftp_server%' AND data->>'src_ip' <> ''  AND (data->>'src_ip') LIKE '%$IP%'\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "table",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT data->'src_ip'->>'ip' as ip,\n       data->'src_ip'->'geo'->> 'city' as city,\n       data->'src_ip'->'geo'->> 'region' as region,\n       data->'src_ip'->'geo'->> 'country' as country,\n       data->'src_ip'->'geo'->> 'asn' as ASN,\n       data->'src_ip'->'geo'->> 'org' as ISP,\n       COUNT(*) as total\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'action' LIKE '%connection%' AND (data->> 'server' LIKE '%https_server%' OR data->> 'server' LIKE '%ftp_server%') AND data->>'src_ip' <> ''  AND (data->>'src_ip') LIKE '%$IP%'\nGROUP BY data->'src_ip'->>'ip',\n       data->'src_ip'->'geo'->> 'city',\n       data->'src_ip'->'geo'->> 'region',\n       data->'src_ip'->'geo'->> 'country',\n       data->'src_ip'->'geo'->> 'asn',\n       data->'src_ip'->'geo'->> 'org';"
    }
   ]
  }
 ]
}